import RPi.GPIO as GPIO
from time import sleep
GPIO.setwarnings(False)
GPIO.setmode(GPIO.BOARD)
GPIO.setup(3,GPIO.OUT)
GPIO.setup(5,GPIO.OUT)
GPIO.setup(7,GPIO.OUT)
p=GPIO.PWM(7,100)
p.start(0)  
while True:
    GPIO.setmode(GPIO.BOARD)
    GPIO.setup(3,GPIO.OUT)
    GPIO.setup(5,GPIO.OUT)
    GPIO.setup(7,GPIO.OUT)
    GPIO.output(3,GPIO.HIGH)
    GPIO.output(5,GPIO.LOW)
    pvalue = int(input("Enter the PWM Value:"))
    p.ChangeDutyCycle(pvalue)
    GPIO.output(7, True)
    sleep (5)
    GPIO.output(7,False)
    GPIO.output(3,False)
    GPIO.output(5,True)
    p.ChangeDutyCycle(pvalue)
    GPIO.output(7, True)
    sleep (5)
    GPIO.output(7,False)
    p.stop()
    GPIO.cleanup()